package youyeluna.lanipscanner.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

/** 支持的语言 */
enum class Language(val code: String, val displayName: String) {
    ZH_CN("zh-CN", "简体中文"),
    ZH_TW("zh-TW", "繁體中文"),
    EN("en", "English")
}

/** 所有可翻译字符串 */
data class Strings(
    // ===== 导航栏 =====
    val navHome: String,
    val navResults: String,
    val navPing: String,

    // ===== 设置 =====
    val settings: String,
    val language: String,
    val save: String,

    // ===== 首页 =====
    val searchRangeTitle: String,
    val startIp: String,
    val endIp: String,
    val startScan: String,
    val stopScan: String,
    val ready: String,
    val scanningIpRange: (String, String) -> String,
    val scanComplete: String,
    val scanStopped: String,
    val scanError: (String) -> String,
    val scanned: String,
    val online: String,
    val noDevice: String,
    val dhcp: String,
    val viewResults: String,

    // ===== 结果页 =====
    val scanning: String,
    val noResults: String,
    val noResultsHint: String,
    val totalIp: String,
    val switchToList: String,
    val switchToGrid: String,
    val export: String,
    val exportSuccess: String,
    val exportFailed: (String) -> String,
    val subnet: String,
    val unscanned: String,
    val gridOnline: String,
    val ipNoResponse: String,
    val close: String,

    // ===== 设备详情 =====
    val ipCount: String,  // 用于摘要 "共 X 个IP"
    val ipAddress: String,
    val macAddress: String,
    val hostName: String,
    val latency: String,
    val dhcpServer: String,
    val yes: String,
    val no: String,
    val status: String,
    val statusOnline: String,
    val statusOffline: String,
    val ping: String,
    val visitBackend: String,

    // ===== Ping 页 =====
    val pingTest: String,
    val targetIp: String,
    val startPing: String,
    val stop: String,
    val clear: String,
    val sent: String,
    val received: String,
    val packetLoss: String,
    val average: String,
    val minimum: String,
    val maximum: String,
    val noPingResults: String,
    val noPingResultsHint: String,
    val pingReply: (String, Int, Long, Int) -> String,
    val pingTimeout: (String) -> String,
    val pingIp: String,
    val pingDomain: String,
    val targetDomain: String,

    // ===== Ping 图表 =====
    val chartLatencyAxis: String,
    val chartTimeAxis: String,
    val chartTimeoutLegend: String,
    val refreshRate: String,

    // ===== 测速页 =====
    val navSpeedTest: String,
    val speedTestTitle: String,
    val speedTestCard: String,
    val startSpeedTest: String,
    val speedTestReady: String,
    val speedTesting: String,
    val speedProgressPercent: (Int) -> String,
    val uploadTesting: String,
    val uploadProgressPercent: (Int) -> String,
    val speedResult: String,
    val speedResultUpload: String,
    val speedTestDuration: String,
    val speedTestDownloaded: String,
    val speedTestUploaded: String,
    val speedTestComplete: String,
    val speedTestHistory: String,
    val noSpeedTestHistory: String,
    val networkError: String,
    val speedTestFailed: (String) -> String,

    // ===== CSV =====
    val csvHeader: String,
    val csvSubnet: String,

    // ===== 排序 =====
    val priorityDisplay: String,
    val normalDisplay: String,

    // ===== MAC 地址限制 =====
    val macWarningTitle: String,
    val macWarningDesc: String,
    val macWarningAck: String,
    val macWarningDialogTitle: String,
    val macWarningDialogMsg: String,

    // ===== 历史 =====
    val navHistory: String,
    val scanHistory: String,
    val noHistory: String,
    val noHistoryHint: String,
    val deleteHistory: String,
    val deleteAllHistory: String,
    val deleteConfirm: String,
    val historyDetail: String,
    val scanTime: String,
    val totalDevices: String,
    val onlineDevices: String,
    val dhcpServers: String,
    val devices: String,
    val cancel: String,
    val delete: String,

    // ===== 数据保存设置 =====
    val dataSaveSettings: String,
    val dataSaveMode: String,
    val scanThreads: String,
    val scanThreadsDesc: String,
    val saveByTime: String,
    val saveByCount: String,
    val saveRange: String,
    val timeRange14Days: String,
    val timeRangeHalfMonth: String,
    val timeRangeOneMonth: String,
    val timeRangeOneYear: String,
    val timeRangeNeverClear: String,
    val timeRangeCustom: String,
    val countRange30: String,
    val countRange60: String,
    val countRange90: String,
    val countRange100: String,
    val daysUnit: String,
    val saveSettings: String,

    // ===== 关于 =====
    val about: String,
    val aboutTitle: String,
    val version: String,
    val description: String,
    val developer: String,
    val copyright: String,
    val openSourceLicenses: String,
    val licenseJSpeedTest: String,
    val githubLink: String
)

/** 简体中文 */
private val ZhCN = Strings(
    navHome = "首页",
    navResults = "结果",
    navPing = "Ping",
    settings = "设置",
    language = "语言",
    save = "保存",
    searchRangeTitle = "搜索范围设置",
    startIp = "起始IP:",
    endIp = "结束IP:",
    startScan = "开始扫描",
    stopScan = "停止扫描",
    ready = "就绪",
    scanningIpRange = { s, e -> "正在扫描 $s ~ $e..." },
    scanComplete = "扫描完成",
    scanStopped = "扫描已停止",
    scanError = { msg -> "扫描出错: $msg" },
    scanned = "已扫",
    online = "在线",
    noDevice = "无设备",
    dhcp = "DHCP",
    viewResults = "查看扫描结果",
    scanning = "正在扫描中...",
    noResults = "暂无扫描结果",
    noResultsHint = "请先在首页设置范围并扫描",
    totalIp = "共",
    switchToList = "切换列表",
    switchToGrid = "切换分布图",
    export = "导出",
    exportSuccess = "导出成功",
    exportFailed = { msg -> "导出失败: $msg" },
    subnet = "网段",
    unscanned = "未扫描",
    gridOnline = "在线",
    ipNoResponse = "未检测",
    close = "关闭",
    ipCount = "个IP",
    ipAddress = "IP地址",
    macAddress = "MAC 地址",
    hostName = "主 机 名",
    latency = "延迟",
    dhcpServer = "DHCP服务器",
    yes = "是",
    no = "否",
    status = "状态",
    statusOnline = "在线",
    statusOffline = "无设备",
    ping = "Ping",
    visitBackend = "访问后台",
    pingTest = "Ping 测试",
    targetIp = "目标IP:",
    startPing = "开始Ping",
    stop = "停止",
    clear = "清空",
    sent = "已发送",
    received = "已接收",
    packetLoss = "丢包率",
    average = "平均",
    minimum = "最小",
    maximum = "最大",
    noPingResults = "暂无 Ping 结果",
    noPingResultsHint = "点击\"开始Ping\"进行测试",
    pingReply = { ip, bytes, rtt, ttl -> "来自 $ip 的回复: 字节=$bytes 时间=${rtt}ms TTL=$ttl" },
    pingTimeout = { ip -> "来自 $ip 的请求超时。" },
    pingIp = "Ping IP",
    pingDomain = "Ping 域名",
    targetDomain = "目标域名:",
    chartLatencyAxis = "延迟 (ms)",
    chartTimeAxis = "时间 (秒)",
    chartTimeoutLegend = "超时",
    refreshRate = "刷新频率",
    navSpeedTest = "测速",
    speedTestTitle = "网速测试",
    speedTestCard = "网速测速",
    startSpeedTest = "开始测速",
    speedTestReady = "准备就绪，点击\"开始测速\"",
    speedTesting = "正在测速...",
    speedProgressPercent = { p -> "已下载 $p%" },
    uploadTesting = "上传测试中...",
    uploadProgressPercent = { p -> "已上传 $p%" },
    speedResult = "下载速度",
    speedResultUpload = "上传速度",
    speedTestDuration = "耗时",
    speedTestDownloaded = "已下载",
    speedTestUploaded = "已上传",
    speedTestComplete = "测速完成",
    speedTestHistory = "测速历史",
    noSpeedTestHistory = "暂无测速记录",
    networkError = "网络异常，请检查网络连接后重试",
    speedTestFailed = { msg -> "测速失败: $msg" },
    csvHeader = "网段,IP地址,MAC地址,主机名,延迟(ms),DHCP服务器,状态",
    csvSubnet = "网段",
    priorityDisplay = "优先显示",
    normalDisplay = "顺序显示",
    about = "关于",
    aboutTitle = "局域网IP扫描器",
    version = "版本",
    description = "一款用于扫描局域网内设备的工具，支持IP扫描、设备识别和Ping测试功能。",
    developer = "开发者",
    copyright = "版权所有",
    openSourceLicenses = "开源许可",
    licenseJSpeedTest = "JSpeedTest (speed-test-lib)\nCopyright (c) 2016-2020 Bertrand Martel\n基于 MIT 许可证授权",
    githubLink = "GitHub 仓库",

    macWarningTitle = "MAC 地址获取受限",
    macWarningDesc = "Android 10 及以上系统限制，无法获取局域网设备的 MAC 地址，需 Root 权限",
    macWarningAck = "知道了",
    macWarningDialogTitle = "功能说明",
    macWarningDialogMsg = "由于 Android 10 及以上版本的隐私安全限制，普通应用无法获取局域网内其他设备的 MAC 地址。\n\n此功能需要设备已 Root 才能正常使用。\n\n其他功能（在线检测、DHCP 服务器识别、Ping 测试等）不受影响。",
    navHistory = "历史",
    scanHistory = "扫描历史",
    noHistory = "暂无扫描历史",
    noHistoryHint = "完成扫描后将自动保存历史记录",
    deleteHistory = "删除历史",
    deleteAllHistory = "清空历史",
    deleteConfirm = "确认删除",
    historyDetail = "历史详情",
    scanTime = "扫描时间",
    totalDevices = "设备总数",
    onlineDevices = "在线设备",
    dhcpServers = "DHCP服务器",
    devices = "设备列表",
    cancel = "取消",
    delete = "删除",

    dataSaveSettings = "数据保存设置",
    dataSaveMode = "数据保存方式",
    scanThreads = "扫描线程数",
    scanThreadsDesc = "并发扫描的线程数（1-100），线程越多扫描越快，但会占用更多系统资源",
    saveByTime = "按时间保存",
    saveByCount = "按数量保存",
    saveRange = "保存范围",
    timeRange14Days = "近14天",
    timeRangeHalfMonth = "半个月",
    timeRangeOneMonth = "一个月",
    timeRangeOneYear = "一年",
    timeRangeNeverClear = "永不清除",
    timeRangeCustom = "自定义天数",
    countRange30 = "近30个",
    countRange60 = "近60个",
    countRange90 = "近90个",
    countRange100 = "近100个",
    daysUnit = "天",
    saveSettings = "保存设置"
)

/** 繁體中文 */
private val ZhTW = Strings(
    navHome = "首頁",
    navResults = "結果",
    navPing = "Ping",
    settings = "設定",
    language = "語言",
    save = "儲存",
    searchRangeTitle = "搜尋範圍設定",
    startIp = "起始IP:",
    endIp = "結束IP:",
    startScan = "開始掃描",
    stopScan = "停止掃描",
    ready = "就緒",
    scanningIpRange = { s, e -> "正在掃描 $s ~ $e..." },
    scanComplete = "掃描完成",
    scanStopped = "掃描已停止",
    scanError = { msg -> "掃描出錯: $msg" },
    scanned = "已掃",
    online = "線上",
    noDevice = "無裝置",
    dhcp = "DHCP",
    viewResults = "查看掃描結果",
    scanning = "正在掃描中...",
    noResults = "暫無掃描結果",
    noResultsHint = "請先在首頁設定範圍並掃描",
    totalIp = "共",
    switchToList = "切換列表",
    switchToGrid = "切換分佈圖",
    export = "匯出",
    exportSuccess = "匯出成功",
    exportFailed = { msg -> "匯出失敗: $msg" },
    subnet = "網段",
    unscanned = "未掃描",
    gridOnline = "線上",
    ipNoResponse = "未偵測",
    close = "關閉",
    ipCount = "個IP",
    ipAddress = "IP位址",
    macAddress = "MAC 位址",
    hostName = "主機名稱",
    latency = "延遲",
    dhcpServer = "DHCP伺服器",
    yes = "是",
    no = "否",
    status = "狀態",
    statusOnline = "線上",
    statusOffline = "無裝置",
    ping = "Ping",
    visitBackend = "訪問後台",
    pingTest = "Ping 測試",
    targetIp = "目標IP:",
    startPing = "開始Ping",
    stop = "停止",
    clear = "清空",
    sent = "已發送",
    received = "已接收",
    packetLoss = "封包遺失率",
    average = "平均",
    minimum = "最小",
    maximum = "最大",
    noPingResults = "暫無 Ping 結果",
    noPingResultsHint = "點擊\"開始Ping\"進行測試",
    pingReply = { ip, bytes, rtt, ttl -> "來自 $ip 的回覆: 位元組=$bytes 時間=${rtt}ms TTL=$ttl" },
    pingTimeout = { ip -> "來自 $ip 的請求逾時。" },
    pingIp = "Ping IP",
    pingDomain = "Ping 網域",
    targetDomain = "目標網域:",
    chartLatencyAxis = "延遲 (ms)",
    chartTimeAxis = "時間 (秒)",
    chartTimeoutLegend = "逾時",
    refreshRate = "刷新頻率",
    navSpeedTest = "測速",
    speedTestTitle = "網速測試",
    speedTestCard = "網速測速",
    startSpeedTest = "開始測速",
    speedTestReady = "準備就緒，點擊\"開始測速\"",
    speedTesting = "正在測速...",
    speedProgressPercent = { p -> "已下載 $p%" },
    uploadTesting = "上傳測試中...",
    uploadProgressPercent = { p -> "已上傳 $p%" },
    speedResult = "下載速度",
    speedResultUpload = "上傳速度",
    speedTestDuration = "耗時",
    speedTestDownloaded = "已下載",
    speedTestUploaded = "已上傳",
    speedTestComplete = "測速完成",
    speedTestHistory = "測速歷史",
    noSpeedTestHistory = "暫無測速記錄",
    scanHistory = "掃描歷史",
    networkError = "網路異常，請檢查網路連線後重試",
    speedTestFailed = { msg -> "測速失敗: $msg" },
    csvHeader = "網段,IP位址,MAC位址,主機名稱,延遲(ms),DHCP伺服器,狀態",
    csvSubnet = "網段",
    priorityDisplay = "優先顯示",
    normalDisplay = "順序顯示",
    about = "關於",
    aboutTitle = "區域網路IP掃描器",
    version = "版本",
    description = "一款用於掃描區域網路內裝置的工具，支援IP掃描、裝置識別和Ping測試功能。",
    developer = "開發者",
    copyright = "版權所有",
    openSourceLicenses = "開源授權",
    licenseJSpeedTest = "JSpeedTest (speed-test-lib)\nCopyright (c) 2016-2020 Bertrand Martel\n基於 MIT 授權條款發佈",
    githubLink = "GitHub 倉庫",

    macWarningTitle = "MAC 位址取得受限",
    macWarningDesc = "Android 10 及以上系統限制，無法取得區域網路裝置的 MAC 位址，需 Root 權限",
    macWarningAck = "知道了",
    macWarningDialogTitle = "功能說明",
    macWarningDialogMsg = "由於 Android 10 及以上版本的隱私安全限制，普通應用無法取得區域網路內其他裝置的 MAC 位址。\n\n此功能需要裝置已 Root 才能正常使用。\n\n其他功能（線上偵測、DHCP 伺服器識別、Ping 測試等）不受影響。",
    navHistory = "歷史",
    noHistory = "暫無掃描歷史",
    noHistoryHint = "完成掃描後將自動儲存歷史記錄",
    deleteHistory = "刪除歷史",
    deleteAllHistory = "清空歷史",
    deleteConfirm = "確認刪除",
    historyDetail = "歷史詳情",
    scanTime = "掃描時間",
    totalDevices = "裝置總數",
    onlineDevices = "線上裝置",
    dhcpServers = "DHCP伺服器",
    devices = "裝置列表",
    cancel = "取消",
    delete = "刪除",

    dataSaveSettings = "資料儲存設定",
    dataSaveMode = "資料儲存方式",
    scanThreads = "掃描執行緒數",
    scanThreadsDesc = "並發掃描的執行緒數（1-100），執行緒越多掃描越快，但會佔用更多系統資源",
    saveByTime = "按時間儲存",
    saveByCount = "按數量儲存",
    saveRange = "儲存範圍",
    timeRange14Days = "近14天",
    timeRangeHalfMonth = "半個月",
    timeRangeOneMonth = "一個月",
    timeRangeOneYear = "一年",
    timeRangeNeverClear = "永不清除",
    timeRangeCustom = "自訂天數",
    countRange30 = "近30個",
    countRange60 = "近60個",
    countRange90 = "近90個",
    countRange100 = "近100個",
    daysUnit = "天",
    saveSettings = "儲存設定"
)

/** English */
private val En = Strings(
    navHome = "Home",
    navResults = "Results",
    navPing = "Ping",
    settings = "Settings",
    language = "Language",
    save = "Save",
    searchRangeTitle = "Scan Range",
    startIp = "Start IP:",
    endIp = "End IP:",
    startScan = "Start Scan",
    stopScan = "Stop Scan",
    ready = "Ready",
    scanningIpRange = { s, e -> "Scanning $s ~ $e..." },
    scanComplete = "Scan Complete",
    scanStopped = "Scan Stopped",
    scanError = { msg -> "Scan Error: $msg" },
    scanned = "Scanned",
    online = "Online",
    noDevice = "No Device",
    dhcp = "DHCP",
    viewResults = "View Results",
    scanning = "Scanning...",
    noResults = "No scan results",
    noResultsHint = "Set range on Home page and start scanning",
    totalIp = "Total",
    switchToList = "Switch to List",
    switchToGrid = "Switch to Grid",
    export = "Export",
    exportSuccess = "Export successful",
    exportFailed = { msg -> "Export failed: $msg" },
    subnet = "Subnet",
    unscanned = "Unscanned",
    gridOnline = "Online",
    ipNoResponse = "Not detected",
    close = "Close",
    ipCount = " IPs",
    ipAddress = "IP Address",
    macAddress = "MAC Address",
    hostName = "Hostname",
    latency = "Latency",
    dhcpServer = "DHCP Server",
    yes = "Yes",
    no = "No",
    status = "Status",
    statusOnline = "Online",
    statusOffline = "No Device",
    ping = "Ping",
    visitBackend = "Visit",
    pingTest = "Ping Test",
    targetIp = "Target IP:",
    startPing = "Start Ping",
    stop = "Stop",
    clear = "Clear",
    sent = "Sent",
    received = "Received",
    packetLoss = "Loss",
    average = "Avg",
    minimum = "Min",
    maximum = "Max",
    noPingResults = "No ping results",
    noPingResultsHint = "Tap \"Start Ping\" to begin",
    pingReply = { ip, bytes, rtt, ttl -> "Reply from $ip: bytes=$bytes time=${rtt}ms TTL=$ttl" },
    pingTimeout = { ip -> "Request timeout from $ip." },
    pingIp = "Ping IP",
    pingDomain = "Ping Domain",
    targetDomain = "Domain:",
    chartLatencyAxis = "Latency (ms)",
    chartTimeAxis = "Time (s)",
    chartTimeoutLegend = "Timeout",
    refreshRate = "Refresh rate",
    navSpeedTest = "Speed",
    speedTestTitle = "Speed Test",
    speedTestCard = "Network Speed Test",
    startSpeedTest = "Start Test",
    speedTestReady = "Ready. Tap \"Start Test\"",
    speedTesting = "Testing...",
    speedProgressPercent = { p -> "Downloaded $p%" },
    uploadTesting = "Upload testing...",
    uploadProgressPercent = { p -> "Uploaded $p%" },
    speedResult = "Download Speed",
    speedResultUpload = "Upload Speed",
    speedTestDuration = "Duration",
    speedTestDownloaded = "Downloaded",
    speedTestUploaded = "Uploaded",
    speedTestComplete = "Test Complete",
    speedTestHistory = "Speed Test History",
    noSpeedTestHistory = "No speed test records yet",
    networkError = "Network error. Please check your connection and try again",
    speedTestFailed = { msg -> "Speed test failed: $msg" },
    csvHeader = "Subnet,IP Address,MAC Address,Hostname,Latency(ms),DHCP Server,Status",
    csvSubnet = "Subnet",
    priorityDisplay = "Priority",
    normalDisplay = "Default Order",
    about = "About",
    aboutTitle = "LAN IP Scanner",
    version = "Version",
    description = "A tool for scanning devices on your local network, supporting IP scanning, device identification, and Ping testing.",
    developer = "Developer",
    copyright = "Copyright",
    openSourceLicenses = "Open Source Licenses",
    licenseJSpeedTest = "JSpeedTest (speed-test-lib)\nCopyright (c) 2016-2020 Bertrand Martel\nLicensed under the MIT License",
    githubLink = "GitHub Repository",

    macWarningTitle = "MAC Address Unavailable",
    macWarningDesc = "Android 10+ restricts MAC address access. Root is required.",
    macWarningAck = "OK",
    macWarningDialogTitle = "Notice",
    macWarningDialogMsg = "Due to Android 10+ privacy restrictions, this app cannot retrieve MAC addresses of other devices on the network.\n\nRoot access is required for this feature.\n\nOther features (online detection, DHCP server identification, Ping test, etc.) are not affected.",
    navHistory = "History",
    scanHistory = "Scan History",
    noHistory = "No scan history",
    noHistoryHint = "History will be saved automatically after scanning",
    deleteHistory = "Delete History",
    deleteAllHistory = "Clear All History",
    deleteConfirm = "Confirm Delete",
    historyDetail = "History Detail",
    scanTime = "Scan Time",
    totalDevices = "Total Devices",
    onlineDevices = "Online Devices",
    dhcpServers = "DHCP Servers",
    devices = "Device List",
    cancel = "Cancel",
    delete = "Delete",

    dataSaveSettings = "Data Save Settings",
    dataSaveMode = "Save Mode",
    scanThreads = "Scan Threads",
    scanThreadsDesc = "Concurrent scan threads (1-100). More threads = faster scan, but uses more resources",
    saveByTime = "Save by Time",
    saveByCount = "Save by Count",
    saveRange = "Save Range",
    timeRange14Days = "Last 14 days",
    timeRangeHalfMonth = "Half month",
    timeRangeOneMonth = "One month",
    timeRangeOneYear = "One year",
    timeRangeNeverClear = "Never clear",
    timeRangeCustom = "Custom days",
    countRange30 = "Last 30",
    countRange60 = "Last 60",
    countRange90 = "Last 90",
    countRange100 = "Last 100",
    daysUnit = "days",
    saveSettings = "Save Settings"
)

/** 根据语言枚举获取对应字符串 */
fun stringsFor(language: Language): Strings = when (language) {
    Language.ZH_CN -> ZhCN
    Language.ZH_TW -> ZhTW
    Language.EN -> En
}

/** CompositionLocal 提供当前语言的字符串 */
val LocalStrings = staticCompositionLocalOf { ZhCN }

/** 便捷访问当前字符串 */
object AppStrings {
    val current: Strings
        @Composable
        @ReadOnlyComposable
        get() = LocalStrings.current
}
